sudo: required

language: php

php:
  - 7.2

services:
  - docker

before_script:
  - ./provision.sh --schema --with-fixtures
  - docker-compose exec -T php.symfony bin/console doctrine:mapping:info
  - docker-compose exec -T php.symfony bin/console doctrine:schema:validate

script:
  - vendor/bin/phpcs -p --colors --standard=PSR2 --extensions=php ./src
  - vendor/bin/phpmd ./src xml cleancode